export const HAMBURGER_MENU="https://cdn-icons-png.flaticon.com/512/9091/9091429.png"
export const YOUTUBE_LOGO="https://www.gstatic.com/youtube/img/branding/youtubelogo/svg/youtubelogo.svg"
export const USER_ICON="https://cdn-icons-png.flaticon.com/128/456/456212.png"
export const SEARCH_ICON = "https://cdn-icons-png.flaticon.com/128/54/54481.png"
export const HOME_ICON="https://cdn-icons-png.flaticon.com/128/2932/2932143.png"
export const SHORTS_ICON="https://cdn-icons-png.flaticon.com/128/5856/5856419.png"
export const SUBSCIPTION_ICON= "https://cdn-icons-png.flaticon.com/128/2989/2989849.png"
export const YOUTUBE_MUSIC="https://www.svgrepo.com/show/520438/youtube-music.svg"
export const YOUTUBE_VIDEOS_API="https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&maxResults=50&regionCode=IN&key="
export const YOUTUBE_SEARCH_API="http://suggestqueries.google.com/complete/search?client=firefox&ds=yt&q="